export const getOrder = (sku: string) => {
  return {
    id: "1",
    startDate: new Date(),
    name: "น้ำดื่มสิงห์ 1500 มล",
    utqName: "แพค6",
    code: "",
    sku: "1",
    ap: "",
    creBy: "touch",
    qty: 150, //(init qty)
    leftQty: 150,
    pending: true, // init value = undefind เพื่อตอนสาขาสั่งแล้วขึ้นเลย
  } as OrderType;
};

export const getOrders = () => {
  return [
    {
      id: "1",
      startDate: new Date(),
      name: "น้ำดื่มสิงห์ 1500 มล",
      utqName: "แพค6",
      code: "8850999320021",
      sku: "1",
      ap: "1",
      creBy: "touch",
      qty: 150,
      leftQty: 150,
      pending: true,
      tag: "",
      branch: "009",
      cat: "น้ำดื่ม",
      brn: "สิงห์",
    },
    {
      id: "2",
      startDate: new Date(),
      name: "น้ำดื่มสิงห์ 600 มล",
      utqName: "แพค12",
      code: "8850999320007",
      sku: "2",
      ap: "1",
      creBy: "touch",
      qty: 200,
      leftQty: 200,
      pending: true,
      tag: "",
      branch: "009",
      cat: "น้ำดื่ม",
      brn: "สิงห์",
    },
    {
      id: "3",
      startDate: new Date(),
      name: "น้ำดื่มสิงห์ 600 มล",
      utqName: "แพค12",
      code: "8850999320007",
      sku: "2",
      ap: "1",
      creBy: "touch",
      qty: 200,
      leftQty: 200,
      pending: true,
      tag: "",
      branch: "008",
      cat: "น้ำดื่ม",
      brn: "สิงห์",
    },
    {
      id: "4",
      startDate: new Date(),
      name: "น้ำดื่มสิงห์ 600 มล",
      utqName: "แพค12",
      code: "8850999320007",
      sku: "2",
      ap: "1",
      creBy: "touch",
      qty: 200,
      leftQty: 200,
      pending: true,
      tag: "",
      branch: "008",
      cat: "น้ำดื่ม",
      brn: "สิงห์",
    },
    {
      id: "5",
      startDate: new Date(),
      name: "ตัวอย่างสินค้าที่ชื่อยาวมาก ถึงมากที่สุด และมันยาวมากจริงๆไม่อยากจะโม้",
      utqName: "กระสอบ*25",
      code: "8850999312345",
      sku: "3",
      ap: "2",
      creBy: "touch",
      qty: 1500,
      leftQty: 1500,
      pending: true,
      tag: "",
      branch: "008",
      cat: "น้ำดื่ม",
      brn: "สิงห์",
    },
  ];
};
