import { Inter } from "next/font/google";
import "./globals.css";
import Container from "./components/Container";
import { AuthProvider } from "./Providers";
import { Metadata } from "next";
import Navbar from "./components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Container>
            <Navbar />
            {children}
          </Container>
        </AuthProvider>
      </body>
    </html>
  );
}
